<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>demo_app</name>
  <version>0.0.1</version>
  <description>Demo application for the mecanum-wheeled mobile platform and rv3sdb robotic arm.
    Supports three control modes for the mobile platform: terminal (typed commands), sequence
    (autonomous), and keyboard (WASD single-key control). Also includes a ROS2 node for a real-time
    keyboard jogging of the rv3sdb arm via moveit?_servo.</description>
  <maintainer email="micanovic.petra@yahoo.com">Petra Micanovic</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>rclpy</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>moveit_servo</exec_depend>
  <exec_depend>moveit_msgs</exec_depend>
  <exec_depend>moveit_py</exec_depend>

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>